"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.YOUME_REACT_NATIVE_EVENT = {
    YOUME_ON_EVENT: "YOUME_ON_EVENT",
    YOUME_ON_RESTAPI: "YOUME_ON_RESTAPI",
    YOUME_ON_MEMBER_CHANGE: "YOUME_ON_MEMBER_CHANGE",
    YOUME_ON_STATISTIC_UPDATE: "YOUME_ON_STATISTIC_UPDATE"
};
/// 事件通知
var YOUME_EVENT_TYPE;
(function (YOUME_EVENT_TYPE) {
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INIT_OK"] = 0] = "YOUME_EVENT_INIT_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INIT_FAILED"] = 1] = "YOUME_EVENT_INIT_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_JOIN_OK"] = 2] = "YOUME_EVENT_JOIN_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_JOIN_FAILED"] = 3] = "YOUME_EVENT_JOIN_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LEAVED_ONE"] = 4] = "YOUME_EVENT_LEAVED_ONE";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LEAVED_ALL"] = 5] = "YOUME_EVENT_LEAVED_ALL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_PAUSED"] = 6] = "YOUME_EVENT_PAUSED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_RESUMED"] = 7] = "YOUME_EVENT_RESUMED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SPEAK_SUCCESS"] = 8] = "YOUME_EVENT_SPEAK_SUCCESS";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SPEAK_FAILED"] = 9] = "YOUME_EVENT_SPEAK_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_RECONNECTING"] = 10] = "YOUME_EVENT_RECONNECTING";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_RECONNECTED"] = 11] = "YOUME_EVENT_RECONNECTED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_REC_PERMISSION_STATUS"] = 12] = "YOUME_EVENT_REC_PERMISSION_STATUS";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_BGM_STOPPED"] = 13] = "YOUME_EVENT_BGM_STOPPED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_BGM_FAILED"] = 14] = "YOUME_EVENT_BGM_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_MIC_ON"] = 16] = "YOUME_EVENT_OTHERS_MIC_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_MIC_OFF"] = 17] = "YOUME_EVENT_OTHERS_MIC_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_SPEAKER_ON"] = 18] = "YOUME_EVENT_OTHERS_SPEAKER_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_SPEAKER_OFF"] = 19] = "YOUME_EVENT_OTHERS_SPEAKER_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VOICE_ON"] = 20] = "YOUME_EVENT_OTHERS_VOICE_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VOICE_OFF"] = 21] = "YOUME_EVENT_OTHERS_VOICE_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MY_MIC_LEVEL"] = 22] = "YOUME_EVENT_MY_MIC_LEVEL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MIC_CTR_ON"] = 23] = "YOUME_EVENT_MIC_CTR_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MIC_CTR_OFF"] = 24] = "YOUME_EVENT_MIC_CTR_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SPEAKER_CTR_ON"] = 25] = "YOUME_EVENT_SPEAKER_CTR_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SPEAKER_CTR_OFF"] = 26] = "YOUME_EVENT_SPEAKER_CTR_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LISTEN_OTHER_ON"] = 27] = "YOUME_EVENT_LISTEN_OTHER_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LISTEN_OTHER_OFF"] = 28] = "YOUME_EVENT_LISTEN_OTHER_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_MIC_ON"] = 29] = "YOUME_EVENT_LOCAL_MIC_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_MIC_OFF"] = 30] = "YOUME_EVENT_LOCAL_MIC_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_SPEAKER_ON"] = 31] = "YOUME_EVENT_LOCAL_SPEAKER_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_SPEAKER_OFF"] = 32] = "YOUME_EVENT_LOCAL_SPEAKER_OFF";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_START_OK"] = 33] = "YOUME_EVENT_GRABMIC_START_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_START_FAILED"] = 34] = "YOUME_EVENT_GRABMIC_START_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_STOP_OK"] = 35] = "YOUME_EVENT_GRABMIC_STOP_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_STOP_FAILED"] = 36] = "YOUME_EVENT_GRABMIC_STOP_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_REQUEST_OK"] = 37] = "YOUME_EVENT_GRABMIC_REQUEST_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_REQUEST_FAILED"] = 38] = "YOUME_EVENT_GRABMIC_REQUEST_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_REQUEST_WAIT"] = 39] = "YOUME_EVENT_GRABMIC_REQUEST_WAIT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_RELEASE_OK"] = 40] = "YOUME_EVENT_GRABMIC_RELEASE_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_RELEASE_FAILED"] = 41] = "YOUME_EVENT_GRABMIC_RELEASE_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_ENDMIC"] = 42] = "YOUME_EVENT_GRABMIC_ENDMIC";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_NOTIFY_START"] = 43] = "YOUME_EVENT_GRABMIC_NOTIFY_START";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_NOTIFY_STOP"] = 44] = "YOUME_EVENT_GRABMIC_NOTIFY_STOP";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_NOTIFY_HASMIC"] = 45] = "YOUME_EVENT_GRABMIC_NOTIFY_HASMIC";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_GRABMIC_NOTIFY_NOMIC"] = 46] = "YOUME_EVENT_GRABMIC_NOTIFY_NOMIC";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_SETOPT_OK"] = 47] = "YOUME_EVENT_INVITEMIC_SETOPT_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_SETOPT_FAILED"] = 48] = "YOUME_EVENT_INVITEMIC_SETOPT_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_REQUEST_OK"] = 49] = "YOUME_EVENT_INVITEMIC_REQUEST_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_REQUEST_FAILED"] = 50] = "YOUME_EVENT_INVITEMIC_REQUEST_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_RESPONSE_OK"] = 51] = "YOUME_EVENT_INVITEMIC_RESPONSE_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_RESPONSE_FAILED"] = 52] = "YOUME_EVENT_INVITEMIC_RESPONSE_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_STOP_OK"] = 53] = "YOUME_EVENT_INVITEMIC_STOP_OK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_STOP_FAILED"] = 54] = "YOUME_EVENT_INVITEMIC_STOP_FAILED";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_CAN_TALK"] = 55] = "YOUME_EVENT_INVITEMIC_CAN_TALK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_CANNOT_TALK"] = 56] = "YOUME_EVENT_INVITEMIC_CANNOT_TALK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_NOTIFY_CALL"] = 57] = "YOUME_EVENT_INVITEMIC_NOTIFY_CALL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_NOTIFY_ANSWER"] = 58] = "YOUME_EVENT_INVITEMIC_NOTIFY_ANSWER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_INVITEMIC_NOTIFY_CANCEL"] = 59] = "YOUME_EVENT_INVITEMIC_NOTIFY_CANCEL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SEND_MESSAGE_RESULT"] = 60] = "YOUME_EVENT_SEND_MESSAGE_RESULT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MESSAGE_NOTIFY"] = 61] = "YOUME_EVENT_MESSAGE_NOTIFY";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_KICK_RESULT"] = 64] = "YOUME_EVENT_KICK_RESULT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_KICK_NOTIFY"] = 65] = "YOUME_EVENT_KICK_NOTIFY";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_FAREND_VOICE_LEVEL"] = 66] = "YOUME_EVENT_FAREND_VOICE_LEVEL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_BE_KICKED"] = 67] = "YOUME_EVENT_OTHERS_BE_KICKED";
    //68-71 talk已占用
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_AUDIO_START_FAIL"] = 72] = "YOUME_EVENT_AUDIO_START_FAIL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_AUDIO_INPUT_DEVICE_CONNECT"] = 73] = "YOUME_EVENT_AUDIO_INPUT_DEVICE_CONNECT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_AUDIO_INPUT_DEVICE_DISCONNECT"] = 74] = "YOUME_EVENT_AUDIO_INPUT_DEVICE_DISCONNECT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SWITCH_OUTPUT"] = 75] = "YOUME_EVENT_SWITCH_OUTPUT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VIDEO_ON"] = 200] = "YOUME_EVENT_OTHERS_VIDEO_ON";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MASK_VIDEO_BY_OTHER_USER"] = 204] = "YOUME_EVENT_MASK_VIDEO_BY_OTHER_USER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_RESUME_VIDEO_BY_OTHER_USER"] = 205] = "YOUME_EVENT_RESUME_VIDEO_BY_OTHER_USER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MASK_VIDEO_FOR_USER"] = 206] = "YOUME_EVENT_MASK_VIDEO_FOR_USER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_RESUME_VIDEO_FOR_USER"] = 207] = "YOUME_EVENT_RESUME_VIDEO_FOR_USER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VIDEO_SHUT_DOWN"] = 208] = "YOUME_EVENT_OTHERS_VIDEO_SHUT_DOWN";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VIDEO_INPUT_START"] = 209] = "YOUME_EVENT_OTHERS_VIDEO_INPUT_START";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_VIDEO_INPUT_STOP"] = 210] = "YOUME_EVENT_OTHERS_VIDEO_INPUT_STOP";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MEDIA_DATA_ROAD_PASS"] = 211] = "YOUME_EVENT_MEDIA_DATA_ROAD_PASS";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_MEDIA_DATA_ROAD_BLOCK"] = 212] = "YOUME_EVENT_MEDIA_DATA_ROAD_BLOCK";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_QUERY_USERS_VIDEO_INFO"] = 213] = "YOUME_EVENT_QUERY_USERS_VIDEO_INFO";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SET_USERS_VIDEO_INFO"] = 214] = "YOUME_EVENT_SET_USERS_VIDEO_INFO";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_VIDEO_INPUT_START"] = 215] = "YOUME_EVENT_LOCAL_VIDEO_INPUT_START";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_VIDEO_INPUT_STOP"] = 216] = "YOUME_EVENT_LOCAL_VIDEO_INPUT_STOP";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_START_PUSH"] = 217] = "YOUME_EVENT_START_PUSH";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_SET_PUSH_MIX"] = 218] = "YOUME_EVENT_SET_PUSH_MIX";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_ADD_PUSH_MIX_USER"] = 219] = "YOUME_EVENT_ADD_PUSH_MIX_USER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHER_SET_PUSH_MIX"] = 220] = "YOUME_EVENT_OTHER_SET_PUSH_MIX";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_SHARE_INPUT_START"] = 221] = "YOUME_EVENT_LOCAL_SHARE_INPUT_START";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_LOCAL_SHARE_INPUT_STOP"] = 222] = "YOUME_EVENT_LOCAL_SHARE_INPUT_STOP";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_SHARE_INPUT_START"] = 223] = "YOUME_EVENT_OTHERS_SHARE_INPUT_START";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_SHARE_INPUT_STOP"] = 224] = "YOUME_EVENT_OTHERS_SHARE_INPUT_STOP";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_DATA_ERROR"] = 300] = "YOUME_EVENT_OTHERS_DATA_ERROR";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_NETWORK_BAD"] = 301] = "YOUME_EVENT_OTHERS_NETWORK_BAD";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_BLACK_FULL"] = 302] = "YOUME_EVENT_OTHERS_BLACK_FULL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_GREEN_FULL"] = 303] = "YOUME_EVENT_OTHERS_GREEN_FULL";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_BLACK_BORDER"] = 304] = "YOUME_EVENT_OTHERS_BLACK_BORDER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_GREEN_BORDER"] = 305] = "YOUME_EVENT_OTHERS_GREEN_BORDER";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_BLURRED_SCREEN"] = 306] = "YOUME_EVENT_OTHERS_BLURRED_SCREEN";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_ENCODER_ERROR"] = 307] = "YOUME_EVENT_OTHERS_ENCODER_ERROR";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_OTHERS_DECODER_ERROR"] = 308] = "YOUME_EVENT_OTHERS_DECODER_ERROR";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_CAMERA_DEVICE_CONNECT"] = 400] = "YOUME_EVENT_CAMERA_DEVICE_CONNECT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_CAMERA_DEVICE_DISCONNECT"] = 401] = "YOUME_EVENT_CAMERA_DEVICE_DISCONNECT";
    YOUME_EVENT_TYPE[YOUME_EVENT_TYPE["YOUME_EVENT_EOF"] = 1000] = "YOUME_EVENT_EOF";
})(YOUME_EVENT_TYPE = exports.YOUME_EVENT_TYPE || (exports.YOUME_EVENT_TYPE = {}));
/// 用户角色
var YOUME_USER_ROLE;
(function (YOUME_USER_ROLE) {
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_NONE"] = 0] = "YOUME_USER_NONE";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_TALKER_FREE"] = 1] = "YOUME_USER_TALKER_FREE";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_TALKER_ON_DEMAND"] = 2] = "YOUME_USER_TALKER_ON_DEMAND";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_LISTENER"] = 3] = "YOUME_USER_LISTENER";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_COMMANDER"] = 4] = "YOUME_USER_COMMANDER";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_HOST"] = 5] = "YOUME_USER_HOST";
    YOUME_USER_ROLE[YOUME_USER_ROLE["YOUME_USER_GUSET"] = 6] = "YOUME_USER_GUSET"; ///< 嘉宾，主播或指挥邀请的连麦嘉宾，同一个时刻只能在一个语音频道里面， 可以随时讲话
})(YOUME_USER_ROLE = exports.YOUME_USER_ROLE || (exports.YOUME_USER_ROLE = {}));
var YOUME_ERROR_CODE;
(function (YOUME_ERROR_CODE) {
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_SUCCESS"] = 0] = "YOUME_SUCCESS";
    // 参数和状态检查
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_API_NOT_SUPPORTED"] = -1] = "YOUME_ERROR_API_NOT_SUPPORTED";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INVALID_PARAM"] = -2] = "YOUME_ERROR_INVALID_PARAM";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_ALREADY_INIT"] = -3] = "YOUME_ERROR_ALREADY_INIT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_NOT_INIT"] = -4] = "YOUME_ERROR_NOT_INIT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_CHANNEL_EXIST"] = -5] = "YOUME_ERROR_CHANNEL_EXIST";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_CHANNEL_NOT_EXIST"] = -6] = "YOUME_ERROR_CHANNEL_NOT_EXIST";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_WRONG_STATE"] = -7] = "YOUME_ERROR_WRONG_STATE";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_NOT_ALLOWED_MOBILE_NETWROK"] = -8] = "YOUME_ERROR_NOT_ALLOWED_MOBILE_NETWROK";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_WRONG_CHANNEL_MODE"] = -9] = "YOUME_ERROR_WRONG_CHANNEL_MODE";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_TOO_MANY_CHANNELS"] = -10] = "YOUME_ERROR_TOO_MANY_CHANNELS";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_TOKEN_ERROR"] = -11] = "YOUME_ERROR_TOKEN_ERROR";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_NOT_IN_CHANNEL"] = -12] = "YOUME_ERROR_NOT_IN_CHANNEL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_BE_KICK"] = -13] = "YOUME_ERROR_BE_KICK";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_DEVICE_NOT_VALID"] = -14] = "YOUME_ERROR_DEVICE_NOT_VALID";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_API_NOT_ALLOWED"] = -15] = "YOUME_ERROR_API_NOT_ALLOWED";
    // 内部操作错误
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_MEMORY_OUT"] = -100] = "YOUME_ERROR_MEMORY_OUT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_START_FAILED"] = -101] = "YOUME_ERROR_START_FAILED";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_STOP_FAILED"] = -102] = "YOUME_ERROR_STOP_FAILED";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_ILLEGAL_SDK"] = -103] = "YOUME_ERROR_ILLEGAL_SDK";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_SERVER_INVALID"] = -104] = "YOUME_ERROR_SERVER_INVALID";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_NETWORK_ERROR"] = -105] = "YOUME_ERROR_NETWORK_ERROR";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_SERVER_INTER_ERROR"] = -106] = "YOUME_ERROR_SERVER_INTER_ERROR";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_QUERY_RESTAPI_FAIL"] = -107] = "YOUME_ERROR_QUERY_RESTAPI_FAIL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_USER_ABORT"] = -108] = "YOUME_ERROR_USER_ABORT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_SEND_MESSAGE_FAIL"] = -109] = "YOUME_ERROR_SEND_MESSAGE_FAIL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_SET_PUSH_PARAM_FAIL"] = -110] = "YOUME_ERROR_SET_PUSH_PARAM_FAIL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INIT_SHARE_FAIL"] = -111] = "YOUME_ERROR_INIT_SHARE_FAIL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_START_SHARE_FAIL"] = -112] = "YOUME_ERROR_START_SHARE_FAIL";
    // 麦克风错误
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_REC_INIT_FAILED"] = -201] = "YOUME_ERROR_REC_INIT_FAILED";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_REC_NO_PERMISSION"] = -202] = "YOUME_ERROR_REC_NO_PERMISSION";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_REC_NO_DATA"] = -203] = "YOUME_ERROR_REC_NO_DATA";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_REC_OTHERS"] = -204] = "YOUME_ERROR_REC_OTHERS";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_REC_PERMISSION_UNDEFINED"] = -205] = "YOUME_ERROR_REC_PERMISSION_UNDEFINED";
    // 抢麦错误
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_GRABMIC_FULL"] = -301] = "YOUME_ERROR_GRABMIC_FULL";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_GRABMIC_HASEND"] = -302] = "YOUME_ERROR_GRABMIC_HASEND";
    // 连麦错误
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INVITEMIC_NOUSER"] = -401] = "YOUME_ERROR_INVITEMIC_NOUSER";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INVITEMIC_OFFLINE"] = -402] = "YOUME_ERROR_INVITEMIC_OFFLINE";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INVITEMIC_REJECT"] = -403] = "YOUME_ERROR_INVITEMIC_REJECT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_INVITEMIC_TIMEOUT"] = -404] = "YOUME_ERROR_INVITEMIC_TIMEOUT";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_CAMERA_OPEN_FAILED"] = -501] = "YOUME_ERROR_CAMERA_OPEN_FAILED";
    YOUME_ERROR_CODE[YOUME_ERROR_CODE["YOUME_ERROR_UNKNOWN"] = -1000] = "YOUME_ERROR_UNKNOWN"; ///< 未知错误
})(YOUME_ERROR_CODE = exports.YOUME_ERROR_CODE || (exports.YOUME_ERROR_CODE = {}));
/// 用户角色
var YOUME_AV_STATISTIC_TYPE;
(function (YOUME_AV_STATISTIC_TYPE) {
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_AUDIO_CODERATE"] = 1] = "YOUME_AVS_AUDIO_CODERATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_CODERATE"] = 2] = "YOUME_AVS_VIDEO_CODERATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_FRAMERATE"] = 3] = "YOUME_AVS_VIDEO_FRAMERATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_AUDIO_PACKET_UP_LOSS_RATE"] = 4] = "YOUME_AVS_AUDIO_PACKET_UP_LOSS_RATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_AUDIO_PACKET_DOWN_LOSS_RATE"] = 5] = "YOUME_AVS_AUDIO_PACKET_DOWN_LOSS_RATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_PACKET_UP_LOSS_RATE"] = 6] = "YOUME_AVS_VIDEO_PACKET_UP_LOSS_RATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_PACKET_DOWN_LOSS_RATE"] = 7] = "YOUME_AVS_VIDEO_PACKET_DOWN_LOSS_RATE";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_AUDIO_DELAY_MS"] = 8] = "YOUME_AVS_AUDIO_DELAY_MS";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_DELAY_MS"] = 9] = "YOUME_AVS_VIDEO_DELAY_MS";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_BLOCK"] = 10] = "YOUME_AVS_VIDEO_BLOCK";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_AUDIO_PACKET_UP_LOSS_HALF"] = 11] = "YOUME_AVS_AUDIO_PACKET_UP_LOSS_HALF";
    YOUME_AV_STATISTIC_TYPE[YOUME_AV_STATISTIC_TYPE["YOUME_AVS_VIDEO_PACKET_UP_LOSS_HALF"] = 12] = "YOUME_AVS_VIDEO_PACKET_UP_LOSS_HALF"; //视频上行的服务器丢包率，千分比
})(YOUME_AV_STATISTIC_TYPE = exports.YOUME_AV_STATISTIC_TYPE || (exports.YOUME_AV_STATISTIC_TYPE = {}));
//# sourceMappingURL=types.js.map